# deployment/kubernetes/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: claude-secrets
  namespace: claude-system
type: Opaque
stringData:
  anthropic-api-key: "YOUR_ANTHROPIC_API_KEY_HERE"
  postgres-url: "postgresql://claude_agi:YOUR_PASSWORD@postgres-service:5432/claude_agi"
  redis-password: "YOUR_REDIS_PASSWORD"
  
  # Additional secrets for Phase 2
  newsapi-key: "YOUR_NEWS_API_KEY"
  
  # Monitoring and alerting
  prometheus-auth-token: "YOUR_PROMETHEUS_TOKEN"
  grafana-admin-password: "YOUR_GRAFANA_PASSWORD"
  
  # Backup encryption
  backup-encryption-key: "YOUR_BACKUP_ENCRYPTION_KEY"
  
  # JWT signing key for API authentication
  jwt-signing-key: "YOUR_JWT_SIGNING_KEY"