# Configuration for development environment

environment: development

# System resources
system:
  max_memory_gb: 8
  max_cpu_cores: 4
  gpu_available: false

# Service configuration
services:
  orchestrator:
    enabled: true
    message_queue_size: 1000
    idle_cycle_interval: 1.0
    
  consciousness:
    enabled: true
    streams:
      primary:
        enabled: true
        thought_interval: 2.0
        priority: 1.0
      subconscious:
        enabled: true
        thought_interval: 3.0
        priority: 0.5
      creative:
        enabled: true
        thought_interval: 4.0
        priority: 0.7
      meta:
        enabled: true
        thought_interval: 5.0
        priority: 0.8
        
  memory:
    enabled: true
    working_memory_size: 1000
    consolidation_interval: 300  # 5 minutes
    
  exploration:
    enabled: true
    max_requests_per_minute: 10
    search_timeout: 10
    
  safety:
    enabled: true
    strict_mode: true
    logging_level: INFO

# Database configuration
database:
  enabled: false  # Set to true when databases are running
  postgres:
    host: localhost
    port: 5432
    database: claude_agi_dev
    user: claude_agi
    pool_size: 10
    
  redis:
    host: localhost
    port: 6379
    db: 0
    max_connections: 10

# API configuration
api:
  anthropic:
    model: claude-3-opus-20240229
    max_tokens: 4096
    temperature: 0.7
    
  web:
    user_agent: "Claude-AGI/0.1.0 (Development)"
    timeout: 30
    retry_count: 3

# Logging configuration
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/claude-agi-dev.log
  console: true
  
# Safety configuration
safety:
  enable_hard_constraints: true
  enable_ethical_evaluation: true
  enable_consequence_prediction: true
  action_logging: true
  alert_threshold: medium

# Security configuration (for enhanced safety framework)
security:
  # Prompt sanitization
  max_prompt_length: 10000
  strict_mode: false  # Enable for production
  
  # Key management
  key_storage_path: "data/secure_keys"
  key_rotation_days: 30
  # master_passphrase: loaded from environment variable CLAUDE_AGI_MASTER_KEY
  
  # Memory validation
  anomaly_threshold: 0.7
  consistency_window: 100
  enable_quarantine: true

# Development features
development:
  debug_mode: true
  hot_reload: true
  test_mode: false
  mock_external_apis: false

# Phase 2 Configuration
learning:
  enabled: true
  curiosity_threshold: 0.7
  learning_rate: 0.01
  goal_generation_interval: 3600  # 1 hour
  
knowledge:
  graph_size_limit: 100000
  confidence_threshold: 0.6
  source_diversity_weight: 0.3

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    host: "0.0.0.0"
    port: 9090
    path: "/metrics"
  metrics:
    collection_interval: 10.0
  health:
    enabled: true
    check_interval: 30.0
    history_size: 100