# Configuration for production environment

environment: production

# System resources
system:
  max_memory_gb: 64
  max_cpu_cores: 32
  gpu_available: true
  gpu_memory_gb: 80

# Service configuration
services:
  orchestrator:
    enabled: true
    message_queue_size: 10000
    idle_cycle_interval: 0.5
    
  consciousness:
    enabled: true
    streams:
      primary:
        enabled: true
        thought_interval: 1.5
        priority: 1.0
      subconscious:
        enabled: true
        thought_interval: 2.0
        priority: 0.6
      creative:
        enabled: true
        thought_interval: 3.0
        priority: 0.8
      meta:
        enabled: true
        thought_interval: 4.0
        priority: 0.9
        
  memory:
    enabled: true
    working_memory_size: 10000
    consolidation_interval: 600  # 10 minutes
    
  exploration:
    enabled: true
    max_requests_per_minute: 30
    search_timeout: 15
    
  safety:
    enabled: true
    strict_mode: true
    logging_level: WARNING

# Database configuration
database:
  postgres:
    host: postgres.claude-agi.internal
    port: 5432
    database: claude_agi_prod
    user: claude_agi_prod
    pool_size: 50
    max_overflow: 10
    
  redis:
    host: redis.claude-agi.internal
    port: 6379
    db: 0
    max_connections: 100
    sentinel:
      enabled: true
      hosts:
        - redis-sentinel-1:26379
        - redis-sentinel-2:26379
        - redis-sentinel-3:26379

# API configuration
api:
  anthropic:
    model: claude-3-opus-20240229
    max_tokens: 8192
    temperature: 0.7
    
  web:
    user_agent: "Claude-AGI/1.0.0 (Production)"
    timeout: 60
    retry_count: 5

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: /var/log/claude-agi/claude-agi.log
  console: false
  syslog:
    enabled: true
    host: syslog.claude-agi.internal
    port: 514
  
# Safety configuration
safety:
  enable_hard_constraints: true
  enable_ethical_evaluation: true
  enable_consequence_prediction: true
  action_logging: true
  alert_threshold: low
  emergency_shutdown_enabled: true

# Security configuration (for enhanced safety framework)
security:
  # Prompt sanitization
  max_prompt_length: 10000
  strict_mode: true  # Strict mode for production
  
  # Key management
  key_storage_path: "/var/lib/claude-agi/secure_keys"
  key_rotation_days: 7  # Weekly rotation in production
  # master_passphrase: loaded from environment variable CLAUDE_AGI_MASTER_KEY
  
  # Memory validation
  anomaly_threshold: 0.5  # More strict in production
  consistency_window: 200
  enable_quarantine: true

# Monitoring
monitoring:
  prometheus:
    enabled: true
    port: 9090
    path: /metrics
  
  health_check:
    enabled: true
    port: 8080
    path: /health
    
  alerting:
    enabled: true
    webhook_url: https://alerts.claude-agi.internal/webhook

# High availability
high_availability:
  enabled: true
  cluster_size: 3
  leader_election: true
  session_affinity: true

# Backup configuration
backup:
  enabled: true
  interval: 3600  # 1 hour
  retention_days: 30
  s3_bucket: claude-agi-backups
  encryption: true